### ISSUE TITLE
Add a license to the package?

### ISSUE THREAD

**Issue by Sciurus365** [jmbh/PanicModel#1]
Hey, thank you for making this model a package! It's now much easier to do simulations. I was wondering, would you consider adding a license to the package so that it's clearer how other researchers (including myself) may modify and reuse it? Thanks : )

**Comment by jmbh** [comment]
Hi, the package already has a license:
https://github.com/jmbh/PanicModel/blob/main/DESCRIPTION#L8C9-L8C20
We encourage other researchers to modify & build on our computational model!
Best,
J

**Comment by Sciurus365** [comment]
Got it, great, thanks! I was looking for a license file but forgot the description file...
